version: '3.4'

services:
  accepts:
    image: accepts
    build:
      context: node_modules/accepts
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
